server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ticket?useSSL=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf: # 前段页面配置（基本都是默认的，可以不用配置）
    cache: false
    prefix: classpath:/templates/
    encoding: UTF-8
    suffix: .html
    mode: HTML
  web:
    resources:
      static-locations: classpath:/templates/,classpath:/static/
  mail: # 邮箱配置
    default-encoding: UTF-8
    host: smtp.163.com
    password: LTTYFROCSUFFDHTA
    port: 465
    protocol: smtps
    username: zxiaoyang777@163.com
  security:
    user:
      name: zhu
      password: 12345



# mybatis 配置
mybatis:
  type-aliases-package: com.zhu.ticketgrabbing.entity
  mapper-locations: classpath:mapper/*.xml
  configuration: # 配置日志输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

project:
  title: 12306抢票项目

url:
  queryApi: https://kyfw.12306.cn/otn/leftTicket/queryZ # 列车票查询 get
  checkLogin: https://kyfw.12306.cn/passport/web/checkLoginVerify  # 登录链接 post username=d'd'd&appid=otn&_json_att=
  messageCode: https://kyfw.12306.cn/passport/web/getMessageCode  # 获取验证码 post appid=otn&username=d'd'd&castNum=3232&_json_att=
  login: https://kyfw.12306.cn/passport/web/login # 登录链接 post

config:
  baseUrl: "https://kyfw.12306.cn/otn/leftTicket/init?linktypeid=wf"
  host: "kyfw.12306.cn"
  enableProxy: false
  appId: "otn"
  proxyHost: "127.0.0.1"
  proxyPort: 8080

thread-pool:
  file:
    corePoolSize: 10
    maximumPoolSize: 30
    keepAliveTime: 300
    queueCapacity: 50
  common:
    corePoolSize: 10
    maximumPoolSize: 30
    keepAliveTime: 300
    queueCapacity: 50